### ISSUE TITLE
`certbot-auto` should not be hard-coded

### ISSUE THREAD

**Issue by evianzhow** [fenying/le-alidns#1]
I've installed certbot using Ubuntu package manager, it was installed under `/usr/bin/certbot`. 
But in your script, `certbot-auto` is hard-coded and I have to create a soft link pointing to `certbot`. I think it's better to specify a executable path instead of directory path?

**Comment by fenying** [comment]
Well thanks for pointing out this. I have made a commit and added the [`certbot-root`](https://github.com/fenying/le-alidns/blob/master/default.conf#L21) option in configuration file, so that you can now specify the name of the certbot command by this option. Enjoy it.
